### ISSUE TITLE
能否添加根据题目 tag 来抽取指定类型题目

### ISSUE THREAD

**Issue by PokIsemaine** [left0ver/qqRot-interview#2]
除了服务器定时任务发送默认题目外，能否添加互动的功能根据群友的消息来抽取特定类型的题目
效果：
> 群友：@qqbot tag:js
服务器检测到群友的消息 "tag:js" 后随机抽取 tag 为 js 的题目
qqbot:@群友 说一下 js 的垃圾回收和其他语言的垃圾回收有什么区别

**Comment by left0ver** [comment]
可以，后续我会加上这个功能，感谢你的建议

**Comment by left0ver** [comment]
> 除了服务器定时任务发送默认题目外，能否添加互动的功能根据群友的消息来抽取特定类型的题目 效果：
> 
> > 群友：@qqbot tag:js
> > 服务器检测到群友的消息 "tag:js" 后随机抽取 tag 为 js 的题目
> > qqbot:@群友 说一下 js 的垃圾回收和其他语言的垃圾回收有什么区别

该功能已经添加，并且添加了许多新特性，see [release](https://github.com/robot-bingbing/qqRot-interview/releases/tag/v1.2.0)
